// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAds68ij1EG5SnQc6j5WHYoTgOr9CLwJNA',
    appId: '1:68283766886:web:3ac7479dfb26668c82f5a7',
    messagingSenderId: '68283766886',
    projectId: 'medrelay-ai',
    authDomain: 'medrelay-ai.firebaseapp.com',
    storageBucket: 'medrelay-ai.firebasestorage.app',
    measurementId: 'G-JTJ4SMTNYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaScWjDyQ8Bqv5AJueit6PJDB9SRnG2z0',
    appId: '1:68283766886:android:203feca72605e63282f5a7',
    messagingSenderId: '68283766886',
    projectId: 'medrelay-ai',
    storageBucket: 'medrelay-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAetoxBMGjxK-TCPjIEkCXxgorVZnPDog',
    appId: '1:68283766886:ios:d8be7fd179eb549d82f5a7',
    messagingSenderId: '68283766886',
    projectId: 'medrelay-ai',
    storageBucket: 'medrelay-ai.firebasestorage.app',
    iosBundleId: 'com.example.medrelayAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAetoxBMGjxK-TCPjIEkCXxgorVZnPDog',
    appId: '1:68283766886:ios:d8be7fd179eb549d82f5a7',
    messagingSenderId: '68283766886',
    projectId: 'medrelay-ai',
    storageBucket: 'medrelay-ai.firebasestorage.app',
    iosBundleId: 'com.example.medrelayAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAds68ij1EG5SnQc6j5WHYoTgOr9CLwJNA',
    appId: '1:68283766886:web:259f5c5a7402b8ad82f5a7',
    messagingSenderId: '68283766886',
    projectId: 'medrelay-ai',
    authDomain: 'medrelay-ai.firebaseapp.com',
    storageBucket: 'medrelay-ai.firebasestorage.app',
    measurementId: 'G-60MNB3L05H',
  );
}
